language: node_js
node_js:
- 6
- 8
- 10

before_install:
- sudo add-apt-repository -y ppa:linuxuprising/java
- sudo apt-get -qq update
- echo debconf shared/accepted-oracle-license-v1-2 select true | sudo debconf-set-selections
- echo debconf shared/accepted-oracle-license-v1-2 seen true | sudo debconf-set-selections
- sudo apt-get install -y oracle-java11-installer

addons:
    apt:
        packages:
        - realpath
