language: node_js
node_js:
- 6
- 8
- 10

before_install:
- sudo add-apt-repository -y ppa:linuxuprising/java
- sudo apt-get -qq update
- sudo apt-get install -y oracle-java10-installer

addons:
    apt:
        packages:
        - realpath
